# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3367b06b82a55a4b2679736debcb42efd5a44f77f79edc0f6ec8e7db0f0780af2c7d2cbf2ce80d516efbeaa1045a8f43440e6924555ab7074e475aec5f1866dc

test:
  secret_key_base: 3229868f316e1e65c23a9c0e59229e9639daef79934d164ba41dfb48a4899bc05a4229aeee489ad177f68b717b3f33ce1f4b52369da7683a4994cb897990b1be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
